/**
 * Loads statements generated by the agents pipeline (data/processed/).
 * There is deliberately no mock fallback: if a race hasn't been generated,
 * it simply has no statements, and the app shows an empty state rather than
 * unsourced placeholder scores about real candidates.
 *
 * Generate them with:
 *   python -m agents.scout
 *   python -m agents.wedge
 */

import { Statement, CandidateBio } from "@/types";

const loaded: Statement[] = [];
let loadedBios: Record<string, CandidateBio> = {};

// One question set for the whole ballot. Static require so the bundler can
// include it at build time; a missing file means it hasn't been generated.
try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const ballot = require("../../data/processed/statements_ballot.json");
    loaded.push(...ballot.statements);
    loadedBios = ballot.bios ?? {};
} catch {}

export const statements: Statement[] = loaded;

/** Sourced candidate backgrounds, keyed by candidate id. */
export const bios: Record<string, CandidateBio> = loadedBios;
