/**
 * Loads statements generated by the agents pipeline (data/processed/).
 * There is deliberately no mock fallback: if a race hasn't been generated,
 * it simply has no statements, and the app shows an empty state rather than
 * unsourced placeholder scores about real candidates.
 *
 * Generate them with:
 *   python -m agents.scout
 *   python -m agents.wedge
 */

import { Statement } from "@/types";

const loaded: Statement[] = [];

// Static requires so the bundler can include each file at build time.
// A missing file just means that race hasn't been generated yet.
try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    loaded.push(...require("../../data/processed/statements_senate.json").statements);
} catch {}
try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    loaded.push(...require("../../data/processed/statements_house_ma7.json").statements);
} catch {}
try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    loaded.push(...require("../../data/processed/statements_governor.json").statements);
} catch {}

export const statements: Statement[] = loaded;
